apiVersion: v1
kind: Pod
metadata:
  name: iscsi-test-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - tail
    agrs:
    - '-f'
    - '/dev/null'
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: final-test-pvc
